export const categories = [
  "system",
  "owner",
  "group",
  "fun",
  "utils",
  "downloads",
  "search",
  "economy",
  "sticker",
  "profile",
  "interaction",
  "AI",
  "stalk",
  "gacha",
];

export const Aliases = {
  descargas: "downloads",
  descarga: "downloads",
  sistema: "system",
  propietario: "owner",
  dueño: "owner",
  owner: "owner",
  grupo: "group",
  grupos: "group",
  diversion: "fun",
  diversiones: "fun",
  diversión: "fun",
  utilidades: "utils",
  utiles: "utils",
  busqueda: "search",
  buscador: "search",
  economia: "economy",
  economía: "economy",
  pegatinas: "sticker",
  stickers: "sticker",
  perfil: "profile",
  interacion: "interaction",
  interacciones: "interaction",
  interacción: "interaction",
  IA: "AI",
  AI: "AI",
  ai: "AI",
  ia: "AI",
  "inteligencia artificial": "AI",
  inteligenciaartificial: "AI",
  stalk: "stalk",
  inspección: "stalk",
  gacha: "gacha",
  waifu: "gacha",
  waifus: "gacha",
  harem: "gacha",
};
