export const economyTexts = {
  work: [
    "Trabajaste como programador y ganaste",
    "Vendiste limonada y ganaste",
    "Ayudaste a una anciana a cruzar la calle y te dio",
    "Reparaste una computadora y cobraste",
    "Trabajaste de mesero y ganaste en propinas",
    "Encontraste dinero en la calle:",
    "Lavaste autos todo el día y conseguiste",
    "Hiciste streaming y recibiste donaciones por",
    "Paseaste perros en el parque y ganaste",
    "Diste clases particulares y cobraste",
    "Trabajaste en la construcción y ganaste",
    "Vendiste cosas que ya no usabas y conseguiste",
    "Hiciste trabajos freelance y ganaste",
    "Ayudaste a un vecino con su jardín y te pagó",
    "Trabajaste en una granja y ganaste",
    "Hiciste entregas en bicicleta y ganaste",
    "Vendiste comida casera y conseguiste",
    "Trabajaste como DJ en una fiesta y ganaste",
    "Hiciste de niñera y cobraste",
    "Vendiste tus dibujos y ganaste",
  ],
  crime: {
    success: [
      "Asaltaste un banco y escapaste con",
      "Robaste la billetera de un millonario y obtuviste",
      "Hackeaste una cuenta de banco y transferiste",
      "Vendiste mercancía dudosa y ganaste",
      "Asaltaste una tienda de conveniencia y huiste con",
      "Robaste un auto deportivo, lo vendiste y ganaste",
      "Hiciste un fraude en línea y obtuviste",
      "Robaste un camión de carga y conseguiste",
      "Asaltaste una joyería y escapaste con",
      "Hackeaste un cajero automático y sacaste",
      "Vendiste información confidencial y ganaste",
      "Robaste un yate de lujo, lo vendiste y ganaste",
      "Hiciste un atraco a mano armada y conseguiste",
      "Asaltaste una mansión y escapaste con",
      "Hackeaste una criptomoneda y obtuviste",
      "Vendiste objetos robados y ganaste",
      "Robaste un avión privado, lo vendiste y ganaste",
      "Asaltaste un casino y escapaste con",
      "Hackeaste una cuenta de PayPal y transferiste",
      "Vendiste drogas ilegales y ganaste",
      "Robaste un banco de sangre y vendiste los órganos por",
      "Asaltaste un museo y escapaste con una obra de arte valiosa que vendiste por",
    ],
    fail: [
      "Te atrapó la policía y tuviste que pagar una fianza de",
      "Una anciana te golpeó con su bolso y perdiste",
      "Te resbalaste mientras huías y se te cayeron",
      "Te estafaron intentando estafar y perdiste",
      "El banco estaba vacío, en el enojo rompiste algo y pagaste",
      "Un perro te persiguió, rasgó tu pantalón y reparar eso costó",
      "Te atrapó un guardia de seguridad y tuviste que pagarle",
      "Te caíste de la bicicleta mientras huías y te rompiste algo que costó",
      "Una cámara de seguridad te grabó, te identificaron y tuviste que pagar una multa de",
      "Te atrapó la policía, te llevaron a la estación y pagaste una multa de",
      "Un transeúnte te vio, llamó a la policía y tuviste que pagar una multa de",
      "Te atrapó un guardia de seguridad, te golpeó y perdiste",
      "Te resbalaste con una cáscara de plátano mientras huías y perdiste",
      "Una anciana te vio intentando robarle, gritó y se asustó tanto que se desmayó, ahora tienes que pagarle su hospitalización por",
      "Te atrapó la policía, te llevaron a la estación y pagaste una multa de",
      "Un transeúnte te vio, llamó a la policía y tuviste que pagar una multa de",
      "Te atrapó un guardia de seguridad, te golpeó y perdiste",
      "Te resbalaste con una cáscara de plátano mientras huías y perdiste",
    ],
  },
  slut: {
    success: [
      "Te fuiste con un anciano millonario y te pagó",
      "Bailaste en un club VIP y ganaste",
      "Vendiste fotos de tus pies y conseguiste",
      "Tuviste una cita con tu Sugar Daddy/Mommy y te dio",
      "Trabajaste en la calle roja y conseguiste",
      "Te pagaron por compañía privada y ganaste",
    ],
    fail: [
      "Tu cliente huyó sin pagarte, y el taxi de regreso te costó",
      "La policía hizo una redada y pagaste una multa de",
      "Te robaron en el callejón oscuro perdiendo",
      "Atrapaste una enfermedad y la medicina costó",
      "El Sugar Daddy resultó ser pobre, invitaste la cena y gastaste",
    ],
  },
  mine: {
    success: [
      "Picaste en una veta profunda y encontraste oro por valor de",
      "Descubriste un depósito de hierro abandonado y lo vendiste por",
      "Mutilaste una roca gigante y extrajiste cristales de cuarzo valorados en",
      "Encontraste restos de una antigua mina enana con pepitas de plata por",
      "Picaste carbón de alta calidad y una herrería te pagó",
      "Rompiste una geoda gigante llena de amatistas que vendiste por",
      "Encontraste un bloque de cobre puro enterrado y te dieron",
      "Desenterraste restos de fósiles antiguos y un museo te dio",
      "Llimpiaste un pozo obstruido y encontraste un cofre viejo con",
      "Mina adentro de una grieta oculta y hallaste esmeraldas por valor de",
      "Picaste un filón de piedra brillante y los científicos te pagaron",
      "Encontraste un meteorito enterrado con metales raros que vendiste por",
      "Extrajiste bauxita de una cueva y una fábrica te pagó",
      "Rompiste una pared falsa y descubriste un alijo de pirita por",
      "Picaste en el lecho de un río subterráneo y sacaste pepitas por",
      "Desenterraste ámbar prehistórico intacto y te pagaron",
      "Encontraste mineral de uranio seguro y una central te dio",
      "Picaste jade oscuro de las paredes rocosas y lo vendiste por",
      "Descubriste un pozo de gemas menores y recolectaste",
      "Rompiste una piedra dura y liberaste un fragmento de topacio por valor de",
    ],
    fail: [
      "Hubo un pequeño derrumbe en la cueva y tuviste que salir corriendo para salvarte.",
      "Se te rompió el pico de hierro al golpear una roca extremadamente dura.",
      "Una bandada de murciélagos te atacó en la oscuridad y te hizo perder el rumbo.",
      "Te caíste en un pozo de lodo subterráneo y terminaste completamente empapado.",
      "Calculaste mal la dinamita y terminaste destruyendo todos los minerales del sector.",
      "El gas de la cueva te mareó por completo y tuviste que salir de emergencia.",
      "Se inundó tu túnel de excavación principal y se perdieron las antorchas.",
      "Un derrumbe repentino bloqueó la salida y esperaste horas al equipo de rescate.",
      "Picaste una tubería vieja de agua por error y causaste una inundación subterránea.",
      "Te picó una araña venenosa de cueva y tuviste que regresar al campamento a descansar.",
      "El soporte de madera de tu túnel cedió por completo, tapando el acceso a la veta.",
      "Dejaste caer tu bolsa de herramientas por una grieta profunda e inalcanzable.",
      "Un duendecillo de las cuevas te saboteó el campamento mientras no estabas mirando.",
      "Hiciste demasiado ruido al picar y una patrulla de la policía ecológica te sacó del lugar.",
      "Te resbalaste con una piedra húmeda y terminaste rodando por una rampa de tierra.",
      "El pico se astilló por completo al chocar contra un enorme bloque de granito sin valor.",
      "Te quedaste sin antorchas a mitad de camino y tuviste que volver a tientas en la oscuridad.",
      "Una fuerte corriente subterránea arrastró parte de tus suministros río abajo.",
      "Olvidaste asegurar tu carretilla, rodó colina abajo y se estrelló contra una pared.",
      "El detector de metales no paraba de fallar y no dio ningún fruto en toda la jornada.",
    ],
  },
  hunt: {
    success: [
      // Minecraft
      "Derrotaste a un Warden usando tu arco con Poder V y el Gremio de Cazadores te pagó",
      "Limpiaste una Shortcut de una Snapshot de Minecraft y vendiste los lingotes de netherite por",
      "Cazaste un Ender Dragon en un servidor Hardcore y los aldeanos te recompensaron con",
      "Mataste a un Wither usando pociones de fuerza y vendiste la estrella del nether por",
      "Emboscaste a un grupo de Pillagers, defendiste la aldea y el inventario te dejó",
      // Brawl Stars
      "Ganaste una partida de Supervivencia Solo usando a Mortis en copas altas y cobraste",
      "Activaste la Hipercarga de Fang, eliminaste a todo el equipo rival en Balón Brawl y ganaste",
      "Derrotaste al Boss del modo Megabrawl usando a Edgar y te dieron un botín de",
      "Hiciste un Team Wipe espectacular con Spike en Noqueo y los patrocinadores te pagaron",
      "Completaste un desafío especial de Desafío de Campeonato y reclamaste",
      // Doors
      "Lograste evadir a Rush escondiéndote perfectamente en el armario y encontraste un fajo de",
      "Superaste la habitación 50 burlando por completo a Figure y saqueaste el mostrador por",
      "Usaste el Crucifijo contra Ambush en el momento exacto y la grieta del hotel te soltó",
      "Sobreviviste a la persecución de Seek sin cometer ningún error de ruta y ganaste",
      "Completaste el Hotel entero cruzando la puerta 100 con vida y la recompensa final fue de",
    ],
    fail: [
      // Minecraft
      "Un Creeper eléctrico saltó desde un árbol detras de ti y te borró el escudo antes de poder atacar.",
      "Te caíste directamente en un pozo de lava dentro de una Nether Fortress perdiendo tus pociones.",
      "Intentaste hacer un MLG con cubo de agua desde una altura masiva, fallaste el timming y moriste.",
      "Un Enderman se enfureció porque lo miraste a los ojos, te arrastró al vacío y perdiste el rastro.",
      "Fuiste emboscado por un Baby Zombie con armadura completa de oro y tuviste que desconectarte.",
      // Brawl Stars
      "Te quedaste campeando en un arbusto y Shelly te borró del mapa usando su Súper a quemarropa.",
      "Intentaste hacer un Trickshot dinámico en Balón Brawl, fallaste el tiro y tu propio equipo te reportó.",
      "Un León usando su gadget de clonación te engañó por completo y te eliminó por la espalda.",
      "Te atrapó la tormenta de gas tóxico en Showdown mientras intentabas recolectar cajas de fuerza.",
      "La Dynamike enemiga predijo todos tus movimientos con sus saltos dinámicos y te dejó fuera de combate.",
      // Doors
      "Apareció Screech en la habitación oscura, no lograste mirarlo a tiempo y te arrancó la mitad de la vida.",
      "Te escondiste demasiado rápido en el armario y la entidad Hide te expulsó directamente hacia Rush.",
      "Fallaste los Quick Time Events en la biblioteca y Figure te atrapó al instante haciendo ruido.",
      "Te equivocaste de puerta durante la persecución de Seek y fuiste consumido por las manos de lodo.",
      "Apareció Jack detrás de la puerta del armario, te asustaste tanto que te quedaste paralizado en el pasillo.",
    ],
  },
  adventure: {
    success: [
      "Completaste una submisión en las Ruinas Olvidadas y el gremio te recompensó con",
      "Derrotaste a un grupo de Duendes de Élite y saqueaste sus cofres por",
      "Protegiste una caravana de comerciantes de un asalto de bandidos y te pagaron",
      "Exploraste una mazmorra secreta de nivel alto y encontraste un botín de",
      "Venciste al subjefe 'Gólem de Cristal' en combate dinámico y dropeó",
      "Completaste un contrato de caza para eliminar un Lobo Huargo y cobraste",
      "Resolviste el acertijo de la Estatua Ancestral y se abrió un compartimento con",
      "Ayudaste al alquimista local a recolectar flores de fuego y te dio",
    ],
    fail: [
      "Te enfrentaste al Jefe de la Zona sin equipamiento adecuado y tuviste que usar un pergamino de teletransporte de emergencia.",
      "Caíste en una trampa de pinchos oculta en la mazmorra y tu poción de curación se rompió en el impacto.",
      "Un mago oscuro de nivel 99 te lanzó un hechizo de sueño y despertaste en la entrada sin tu bolsa de provisiones.",
      "Intentaste abrir un cofre trampa (Mimic), casi te devora y tuviste que huir perdiendo el rastro de la misión.",
      "Te perdiste en el Bosque de la Niebla y gastaste todo el día intentando encontrar el camino de regreso al spawn.",
      "El jefe de la mazmorra esquivó tu ataque crítico con 1 HP restante y te obligó a realizar una retirada táctica.",
    ],
  },
};
